#!/bin/bash

./rama input_pdb/1A1D_A.pdb -o output_rama/1A1D_A.txt
./rama input_pdb/1A1Q_B.pdb -o output_rama/1A1Q_B.txt
./rama input_pdb/1A1Q_C.pdb -o output_rama/1A1Q_C.txt
./rama input_pdb/1A1Q_A.pdb -o output_rama/1A1Q_A.txt
./rama input_pdb/1A02_J.pdb -o output_rama/1A02_J.txt
./rama input_pdb/1A02_F.pdb -o output_rama/1A02_F.txt
./rama input_pdb/1A15_B.pdb -o output_rama/1A15_B.txt
./rama input_pdb/1A1U_A.pdb -o output_rama/1A1U_A.txt
./rama input_pdb/1A1U_C.pdb -o output_rama/1A1U_C.txt
./rama input_pdb/1A0A_A.pdb -o output_rama/1A0A_A.txt
./rama input_pdb/1A0A_B.pdb -o output_rama/1A0A_B.txt
./rama input_pdb/1A0O_D.pdb -o output_rama/1A0O_D.txt
./rama input_pdb/1A0O_H.pdb -o output_rama/1A0O_H.txt
./rama input_pdb/1A0O_F.pdb -o output_rama/1A0O_F.txt
./rama input_pdb/1A0O_B.pdb -o output_rama/1A0O_B.txt
./rama input_pdb/1A0R_G.pdb -o output_rama/1A0R_G.txt
./rama input_pdb/1A15_A.pdb -o output_rama/1A15_A.txt
./rama input_pdb/1A1F_A.pdb -o output_rama/1A1F_A.txt
./rama input_pdb/1A1G_A.pdb -o output_rama/1A1G_A.txt
./rama input_pdb/1A1J_A.pdb -o output_rama/1A1J_A.txt
./rama input_pdb/1A1H_A.pdb -o output_rama/1A1H_A.txt
./rama input_pdb/1A1I_A.pdb -o output_rama/1A1I_A.txt
./rama input_pdb/1A1K_A.pdb -o output_rama/1A1K_A.txt
./rama input_pdb/1A1L_A.pdb -o output_rama/1A1L_A.txt
./rama input_pdb/1A19_A.pdb -o output_rama/1A19_A.txt
./rama input_pdb/1A19_B.pdb -o output_rama/1A19_B.txt
./rama input_pdb/1A14_L.pdb -o output_rama/1A14_L.txt
./rama input_pdb/1A1T_A.pdb -o output_rama/1A1T_A.txt
./rama input_pdb/1A1M_B.pdb -o output_rama/1A1M_B.txt
./rama input_pdb/1A1N_B.pdb -o output_rama/1A1N_B.txt
./rama input_pdb/1A1O_B.pdb -o output_rama/1A1O_B.txt
./rama input_pdb/1A0N_B.pdb -o output_rama/1A0N_B.txt
./rama input_pdb/1A1X_A.pdb -o output_rama/1A1X_A.txt
./rama input_pdb/1A1C_B.pdb -o output_rama/1A1C_B.txt
./rama input_pdb/1A1B_B.pdb -o output_rama/1A1B_B.txt
./rama input_pdb/1A1E_B.pdb -o output_rama/1A1E_B.txt
./rama input_pdb/1A08_B.pdb -o output_rama/1A08_B.txt
./rama input_pdb/1A09_B.pdb -o output_rama/1A09_B.txt
./rama input_pdb/1A1A_B.pdb -o output_rama/1A1A_B.txt
./rama input_pdb/1A1B_A.pdb -o output_rama/1A1B_A.txt
./rama input_pdb/1A08_A.pdb -o output_rama/1A08_A.txt
./rama input_pdb/1A0B_A.pdb -o output_rama/1A0B_A.txt
./rama input_pdb/1A07_B.pdb -o output_rama/1A07_B.txt
./rama input_pdb/1A1E_A.pdb -o output_rama/1A1E_A.txt
./rama input_pdb/1A07_A.pdb -o output_rama/1A07_A.txt
./rama input_pdb/1A1C_A.pdb -o output_rama/1A1C_A.txt
./rama input_pdb/11BA_A.pdb -o output_rama/11BA_A.txt
./rama input_pdb/11BA_B.pdb -o output_rama/11BA_B.txt
./rama input_pdb/11BG_A.pdb -o output_rama/11BG_A.txt
./rama input_pdb/11BG_B.pdb -o output_rama/11BG_B.txt
./rama input_pdb/1A09_A.pdb -o output_rama/1A09_A.txt
./rama input_pdb/1A1A_A.pdb -o output_rama/1A1A_A.txt
./rama input_pdb/155C_A.pdb -o output_rama/155C_A.txt
./rama input_pdb/1A0O_A.pdb -o output_rama/1A0O_A.txt
./rama input_pdb/1A0O_C.pdb -o output_rama/1A0O_C.txt
./rama input_pdb/1A0O_E.pdb -o output_rama/1A0O_E.txt
./rama input_pdb/1A0O_G.pdb -o output_rama/1A0O_G.txt
./rama input_pdb/135L_A.pdb -o output_rama/135L_A.txt
./rama input_pdb/132L_A.pdb -o output_rama/132L_A.txt
./rama input_pdb/193L_A.pdb -o output_rama/193L_A.txt
./rama input_pdb/194L_A.pdb -o output_rama/194L_A.txt
./rama input_pdb/1A18_A.pdb -o output_rama/1A18_A.txt
./rama input_pdb/1A14_H.pdb -o output_rama/1A14_H.txt
./rama input_pdb/134L_A.pdb -o output_rama/134L_A.txt
./rama input_pdb/133L_A.pdb -o output_rama/133L_A.txt
./rama input_pdb/1A00_A.pdb -o output_rama/1A00_A.txt
./rama input_pdb/1A00_C.pdb -o output_rama/1A00_C.txt
./rama input_pdb/1A0U_A.pdb -o output_rama/1A0U_A.txt
./rama input_pdb/1A0U_C.pdb -o output_rama/1A0U_C.txt
./rama input_pdb/1A0Z_A.pdb -o output_rama/1A0Z_A.txt
./rama input_pdb/1A0Z_C.pdb -o output_rama/1A0Z_C.txt
./rama input_pdb/1A01_A.pdb -o output_rama/1A01_A.txt
./rama input_pdb/1A01_C.pdb -o output_rama/1A01_C.txt
./rama input_pdb/1A0K_A.pdb -o output_rama/1A0K_A.txt
./rama input_pdb/1A01_B.pdb -o output_rama/1A01_B.txt
./rama input_pdb/1A01_D.pdb -o output_rama/1A01_D.txt
./rama input_pdb/1A00_B.pdb -o output_rama/1A00_B.txt
./rama input_pdb/1A00_D.pdb -o output_rama/1A00_D.txt
./rama input_pdb/1A0U_B.pdb -o output_rama/1A0U_B.txt
./rama input_pdb/1A0U_D.pdb -o output_rama/1A0U_D.txt
./rama input_pdb/1A0Z_B.pdb -o output_rama/1A0Z_B.txt
./rama input_pdb/1A0Z_D.pdb -o output_rama/1A0Z_D.txt
./rama input_pdb/104M_A.pdb -o output_rama/104M_A.txt
./rama input_pdb/105M_A.pdb -o output_rama/105M_A.txt
./rama input_pdb/102M_A.pdb -o output_rama/102M_A.txt
./rama input_pdb/103M_A.pdb -o output_rama/103M_A.txt
./rama input_pdb/101M_A.pdb -o output_rama/101M_A.txt
./rama input_pdb/109M_A.pdb -o output_rama/109M_A.txt
./rama input_pdb/110M_A.pdb -o output_rama/110M_A.txt
./rama input_pdb/111M_A.pdb -o output_rama/111M_A.txt
./rama input_pdb/112M_A.pdb -o output_rama/112M_A.txt
./rama input_pdb/106M_A.pdb -o output_rama/106M_A.txt
./rama input_pdb/107M_A.pdb -o output_rama/107M_A.txt
./rama input_pdb/108M_A.pdb -o output_rama/108M_A.txt
./rama input_pdb/1A1R_A.pdb -o output_rama/1A1R_A.txt
./rama input_pdb/1A0H_A.pdb -o output_rama/1A0H_A.txt
./rama input_pdb/1A0H_D.pdb -o output_rama/1A0H_D.txt
./rama input_pdb/169L_A.pdb -o output_rama/169L_A.txt
./rama input_pdb/169L_B.pdb -o output_rama/169L_B.txt
./rama input_pdb/169L_C.pdb -o output_rama/169L_C.txt
./rama input_pdb/169L_D.pdb -o output_rama/169L_D.txt
./rama input_pdb/169L_E.pdb -o output_rama/169L_E.txt
./rama input_pdb/1A1Z_A.pdb -o output_rama/1A1Z_A.txt
./rama input_pdb/192L_A.pdb -o output_rama/192L_A.txt
./rama input_pdb/157L_A.pdb -o output_rama/157L_A.txt
./rama input_pdb/174L_B.pdb -o output_rama/174L_B.txt
./rama input_pdb/103L_A.pdb -o output_rama/103L_A.txt
./rama input_pdb/1A1W_A.pdb -o output_rama/1A1W_A.txt
./rama input_pdb/191L_A.pdb -o output_rama/191L_A.txt
./rama input_pdb/1A17_A.pdb -o output_rama/1A17_A.txt
./rama input_pdb/159L_A.pdb -o output_rama/159L_A.txt
./rama input_pdb/151L_A.pdb -o output_rama/151L_A.txt
./rama input_pdb/150L_B.pdb -o output_rama/150L_B.txt
./rama input_pdb/156L_A.pdb -o output_rama/156L_A.txt
./rama input_pdb/190L_A.pdb -o output_rama/190L_A.txt
./rama input_pdb/142L_A.pdb -o output_rama/142L_A.txt
./rama input_pdb/158L_A.pdb -o output_rama/158L_A.txt
./rama input_pdb/177L_A.pdb -o output_rama/177L_A.txt
./rama input_pdb/178L_A.pdb -o output_rama/178L_A.txt
./rama input_pdb/164L_A.pdb -o output_rama/164L_A.txt
./rama input_pdb/174L_A.pdb -o output_rama/174L_A.txt
./rama input_pdb/175L_A.pdb -o output_rama/175L_A.txt
./rama input_pdb/143L_A.pdb -o output_rama/143L_A.txt
./rama input_pdb/147L_A.pdb -o output_rama/147L_A.txt
./rama input_pdb/150L_C.pdb -o output_rama/150L_C.txt
./rama input_pdb/150L_D.pdb -o output_rama/150L_D.txt
./rama input_pdb/162L_A.pdb -o output_rama/162L_A.txt
./rama input_pdb/163L_A.pdb -o output_rama/163L_A.txt
./rama input_pdb/168L_A.pdb -o output_rama/168L_A.txt
./rama input_pdb/168L_B.pdb -o output_rama/168L_B.txt
./rama input_pdb/168L_C.pdb -o output_rama/168L_C.txt
./rama input_pdb/168L_D.pdb -o output_rama/168L_D.txt
./rama input_pdb/168L_E.pdb -o output_rama/168L_E.txt
./rama input_pdb/171L_A.pdb -o output_rama/171L_A.txt
./rama input_pdb/140L_A.pdb -o output_rama/140L_A.txt
./rama input_pdb/155L_A.pdb -o output_rama/155L_A.txt
./rama input_pdb/160L_A.pdb -o output_rama/160L_A.txt
./rama input_pdb/161L_A.pdb -o output_rama/161L_A.txt
./rama input_pdb/181L_A.pdb -o output_rama/181L_A.txt
./rama input_pdb/182L_A.pdb -o output_rama/182L_A.txt
./rama input_pdb/183L_A.pdb -o output_rama/183L_A.txt
./rama input_pdb/184L_A.pdb -o output_rama/184L_A.txt
./rama input_pdb/185L_A.pdb -o output_rama/185L_A.txt
./rama input_pdb/186L_A.pdb -o output_rama/186L_A.txt
./rama input_pdb/187L_A.pdb -o output_rama/187L_A.txt
./rama input_pdb/188L_A.pdb -o output_rama/188L_A.txt
./rama input_pdb/197L_A.pdb -o output_rama/197L_A.txt
./rama input_pdb/107L_A.pdb -o output_rama/107L_A.txt
./rama input_pdb/166L_A.pdb -o output_rama/166L_A.txt
./rama input_pdb/173L_A.pdb -o output_rama/173L_A.txt
./rama input_pdb/130L_A.pdb -o output_rama/130L_A.txt
./rama input_pdb/131L_A.pdb -o output_rama/131L_A.txt
./rama input_pdb/139L_A.pdb -o output_rama/139L_A.txt
./rama input_pdb/165L_A.pdb -o output_rama/165L_A.txt
./rama input_pdb/126L_A.pdb -o output_rama/126L_A.txt
./rama input_pdb/127L_A.pdb -o output_rama/127L_A.txt
./rama input_pdb/128L_A.pdb -o output_rama/128L_A.txt
./rama input_pdb/198L_A.pdb -o output_rama/198L_A.txt
./rama input_pdb/199L_A.pdb -o output_rama/199L_A.txt
./rama input_pdb/112L_A.pdb -o output_rama/112L_A.txt
./rama input_pdb/114L_A.pdb -o output_rama/114L_A.txt
./rama input_pdb/115L_A.pdb -o output_rama/115L_A.txt
./rama input_pdb/118L_A.pdb -o output_rama/118L_A.txt
./rama input_pdb/119L_A.pdb -o output_rama/119L_A.txt
./rama input_pdb/120L_A.pdb -o output_rama/120L_A.txt
./rama input_pdb/122L_A.pdb -o output_rama/122L_A.txt
./rama input_pdb/123L_A.pdb -o output_rama/123L_A.txt
./rama input_pdb/125L_A.pdb -o output_rama/125L_A.txt
./rama input_pdb/138L_A.pdb -o output_rama/138L_A.txt
./rama input_pdb/141L_A.pdb -o output_rama/141L_A.txt
./rama input_pdb/108L_A.pdb -o output_rama/108L_A.txt
./rama input_pdb/110L_A.pdb -o output_rama/110L_A.txt
./rama input_pdb/111L_A.pdb -o output_rama/111L_A.txt
./rama input_pdb/129L_A.pdb -o output_rama/129L_A.txt
./rama input_pdb/148L_E.pdb -o output_rama/148L_E.txt
./rama input_pdb/180L_A.pdb -o output_rama/180L_A.txt
./rama input_pdb/109L_A.pdb -o output_rama/109L_A.txt
./rama input_pdb/195L_A.pdb -o output_rama/195L_A.txt
./rama input_pdb/196L_A.pdb -o output_rama/196L_A.txt
./rama input_pdb/113L_A.pdb -o output_rama/113L_A.txt
./rama input_pdb/137L_A.pdb -o output_rama/137L_A.txt
./rama input_pdb/102L_A.pdb -o output_rama/102L_A.txt
./rama input_pdb/144L_A.pdb -o output_rama/144L_A.txt
./rama input_pdb/146L_A.pdb -o output_rama/146L_A.txt
./rama input_pdb/145L_A.pdb -o output_rama/145L_A.txt
./rama input_pdb/152L_A.pdb -o output_rama/152L_A.txt
./rama input_pdb/150L_A.pdb -o output_rama/150L_A.txt
./rama input_pdb/175L_B.pdb -o output_rama/175L_B.txt
./rama input_pdb/104L_A.pdb -o output_rama/104L_A.txt
./rama input_pdb/104L_B.pdb -o output_rama/104L_B.txt
./rama input_pdb/167L_A.pdb -o output_rama/167L_A.txt
./rama input_pdb/167L_B.pdb -o output_rama/167L_B.txt
./rama input_pdb/172L_A.pdb -o output_rama/172L_A.txt
./rama input_pdb/176L_A.pdb -o output_rama/176L_A.txt
./rama input_pdb/176L_B.pdb -o output_rama/176L_B.txt
./rama input_pdb/149L_A.pdb -o output_rama/149L_A.txt
./rama input_pdb/170L_A.pdb -o output_rama/170L_A.txt
./rama input_pdb/180L_B.pdb -o output_rama/180L_B.txt
./rama input_pdb/189L_A.pdb -o output_rama/189L_A.txt
./rama input_pdb/137L_B.pdb -o output_rama/137L_B.txt
./rama input_pdb/121P_A.pdb -o output_rama/121P_A.txt
./rama input_pdb/1A03_A.pdb -o output_rama/1A03_A.txt
./rama input_pdb/1A03_B.pdb -o output_rama/1A03_B.txt
./rama input_pdb/1914_A.pdb -o output_rama/1914_A.txt
./rama input_pdb/153L_A.pdb -o output_rama/153L_A.txt
./rama input_pdb/154L_A.pdb -o output_rama/154L_A.txt
./rama input_pdb/1A1R_B.pdb -o output_rama/1A1R_B.txt
./rama input_pdb/1A0R_P.pdb -o output_rama/1A0R_P.txt
./rama input_pdb/14GS_A.pdb -o output_rama/14GS_A.txt
./rama input_pdb/14GS_B.pdb -o output_rama/14GS_B.txt
./rama input_pdb/1A0Q_H.pdb -o output_rama/1A0Q_H.txt
./rama input_pdb/1A21_A.pdb -o output_rama/1A21_A.txt
./rama input_pdb/1A04_A.pdb -o output_rama/1A04_A.txt
./rama input_pdb/1A04_B.pdb -o output_rama/1A04_B.txt
./rama input_pdb/1A0F_A.pdb -o output_rama/1A0F_A.txt
./rama input_pdb/1A0F_B.pdb -o output_rama/1A0F_B.txt
./rama input_pdb/15C8_H.pdb -o output_rama/15C8_H.txt
./rama input_pdb/17GS_B.pdb -o output_rama/17GS_B.txt
./rama input_pdb/10GS_A.pdb -o output_rama/10GS_A.txt
./rama input_pdb/10GS_B.pdb -o output_rama/10GS_B.txt
./rama input_pdb/19GS_A.pdb -o output_rama/19GS_A.txt
./rama input_pdb/19GS_B.pdb -o output_rama/19GS_B.txt
./rama input_pdb/11GS_A.pdb -o output_rama/11GS_A.txt
./rama input_pdb/11GS_B.pdb -o output_rama/11GS_B.txt
./rama input_pdb/12GS_A.pdb -o output_rama/12GS_A.txt
./rama input_pdb/12GS_B.pdb -o output_rama/12GS_B.txt
./rama input_pdb/13GS_B.pdb -o output_rama/13GS_B.txt
./rama input_pdb/16GS_A.pdb -o output_rama/16GS_A.txt
./rama input_pdb/16GS_B.pdb -o output_rama/16GS_B.txt
./rama input_pdb/18GS_A.pdb -o output_rama/18GS_A.txt
./rama input_pdb/18GS_B.pdb -o output_rama/18GS_B.txt
./rama input_pdb/15C8_L.pdb -o output_rama/15C8_L.txt
./rama input_pdb/17GS_A.pdb -o output_rama/17GS_A.txt
./rama input_pdb/1A0Q_L.pdb -o output_rama/1A0Q_L.txt
./rama input_pdb/13GS_A.pdb -o output_rama/13GS_A.txt
./rama input_pdb/12E8_L.pdb -o output_rama/12E8_L.txt
./rama input_pdb/12E8_M.pdb -o output_rama/12E8_M.txt
./rama input_pdb/1A0J_A.pdb -o output_rama/1A0J_A.txt
./rama input_pdb/1A0J_B.pdb -o output_rama/1A0J_B.txt
./rama input_pdb/1A0J_C.pdb -o output_rama/1A0J_C.txt
./rama input_pdb/1A0J_D.pdb -o output_rama/1A0J_D.txt
./rama input_pdb/12E8_H.pdb -o output_rama/12E8_H.txt
./rama input_pdb/12E8_P.pdb -o output_rama/12E8_P.txt
./rama input_pdb/1A0L_A.pdb -o output_rama/1A0L_A.txt
./rama input_pdb/1A0L_B.pdb -o output_rama/1A0L_B.txt
./rama input_pdb/1A0L_C.pdb -o output_rama/1A0L_C.txt
./rama input_pdb/1A0L_D.pdb -o output_rama/1A0L_D.txt
./rama input_pdb/12CA_A.pdb -o output_rama/12CA_A.txt
./rama input_pdb/1A0H_B.pdb -o output_rama/1A0H_B.txt
./rama input_pdb/1A0H_E.pdb -o output_rama/1A0H_E.txt
./rama input_pdb/19HC_A.pdb -o output_rama/19HC_A.txt
./rama input_pdb/19HC_B.pdb -o output_rama/19HC_B.txt
./rama input_pdb/1A02_N.pdb -o output_rama/1A02_N.txt
./rama input_pdb/1A0P_A.pdb -o output_rama/1A0P_A.txt
./rama input_pdb/1A06_A.pdb -o output_rama/1A06_A.txt
./rama input_pdb/117E_A.pdb -o output_rama/117E_A.txt
./rama input_pdb/117E_B.pdb -o output_rama/117E_B.txt
./rama input_pdb/1A0G_A.pdb -o output_rama/1A0G_A.txt
./rama input_pdb/1A1N_A.pdb -o output_rama/1A1N_A.txt
./rama input_pdb/1A1O_A.pdb -o output_rama/1A1O_A.txt
./rama input_pdb/1A0G_B.pdb -o output_rama/1A0G_B.txt
./rama input_pdb/1A1M_A.pdb -o output_rama/1A1M_A.txt
./rama input_pdb/1A1S_A.pdb -o output_rama/1A1S_A.txt
./rama input_pdb/16VP_A.pdb -o output_rama/16VP_A.txt
./rama input_pdb/11AS_A.pdb -o output_rama/11AS_A.txt
./rama input_pdb/11AS_B.pdb -o output_rama/11AS_B.txt
./rama input_pdb/12AS_A.pdb -o output_rama/12AS_A.txt
./rama input_pdb/12AS_B.pdb -o output_rama/12AS_B.txt
./rama input_pdb/10MH_A.pdb -o output_rama/10MH_A.txt
./rama input_pdb/1A0R_B.pdb -o output_rama/1A0R_B.txt
./rama input_pdb/1A0I_A.pdb -o output_rama/1A0I_A.txt
./rama input_pdb/1A05_A.pdb -o output_rama/1A05_A.txt
./rama input_pdb/1A05_B.pdb -o output_rama/1A05_B.txt
./rama input_pdb/1A12_A.pdb -o output_rama/1A12_A.txt
./rama input_pdb/1A12_B.pdb -o output_rama/1A12_B.txt
./rama input_pdb/1A12_C.pdb -o output_rama/1A12_C.txt
./rama input_pdb/1A14_N.pdb -o output_rama/1A14_N.txt
./rama input_pdb/13PK_A.pdb -o output_rama/13PK_A.txt
./rama input_pdb/13PK_B.pdb -o output_rama/13PK_B.txt
./rama input_pdb/13PK_C.pdb -o output_rama/13PK_C.txt
./rama input_pdb/13PK_D.pdb -o output_rama/13PK_D.txt
./rama input_pdb/16PK_A.pdb -o output_rama/16PK_A.txt
./rama input_pdb/1A0S_P.pdb -o output_rama/1A0S_P.txt
./rama input_pdb/1A0S_Q.pdb -o output_rama/1A0S_Q.txt
./rama input_pdb/1A0S_R.pdb -o output_rama/1A0S_R.txt
./rama input_pdb/1A0T_P.pdb -o output_rama/1A0T_P.txt
./rama input_pdb/1A0T_Q.pdb -o output_rama/1A0T_Q.txt
./rama input_pdb/1A0T_R.pdb -o output_rama/1A0T_R.txt
./rama input_pdb/1A1V_A.pdb -o output_rama/1A1V_A.txt
./rama input_pdb/1A0D_A.pdb -o output_rama/1A0D_A.txt
./rama input_pdb/1A0D_B.pdb -o output_rama/1A0D_B.txt
./rama input_pdb/1A0D_C.pdb -o output_rama/1A0D_C.txt
./rama input_pdb/1A0D_D.pdb -o output_rama/1A0D_D.txt
./rama input_pdb/1A16_A.pdb -o output_rama/1A16_A.txt
./rama input_pdb/1A0C_A.pdb -o output_rama/1A0C_A.txt
./rama input_pdb/1A0C_B.pdb -o output_rama/1A0C_B.txt
./rama input_pdb/1A0C_C.pdb -o output_rama/1A0C_C.txt
./rama input_pdb/1A0C_D.pdb -o output_rama/1A0C_D.txt
./rama input_pdb/1A0E_A.pdb -o output_rama/1A0E_A.txt
./rama input_pdb/1A0E_D.pdb -o output_rama/1A0E_D.txt